eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

microservices:
  orderservice: 
    endpoints:
      endpoint:
        bookOrderUri: http://ORDER-SERVICE/order/bookOrder
  paymentservice: 
    endpoints:
      endpoint:
        doPaymentUri: http://PAYMENT-SERVICE/payment/doPayment
      endpoint:
        doPaymentUri: http://PAYMENT-SERVICE/payment
